// Generates the two artefacts that let the app run without the Node server:
//   public/engine.bundle.js  data + engine for the browser (used by public/index.html when /api is unreachable)
//   index.html (repo root)   one self-contained file: engine + dashboard inlined; open it directly or host anywhere
// Run: npm run build      Verify committed files are current: node tools/build-single.js --check
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const need=(c,m)=>{if(!c)throw new Error('build: '+m)};
const wrap=(n,code)=>`const ${n}=(()=>{const module={exports:{}};\n${code}\nreturn module.exports})();`;
const data=read('lib/data.js'),eng=read('lib/engine.js').replace("require('./data')",'globalThis.__DATA');
const engineJs=wrap('D',data)+'\nglobalThis.__DATA=D;\n'+wrap('E',eng)+'\n';

// 1) browser engine bundle
const bundle='// GENERATED by tools/build-single.js - do not edit.\n(function(){\n'+engineJs+'window.CompEngine=E;\n})();\n';

// 2) single-file app
let html=read('public/index.html');
const a=html.indexOf('/*API-BEGIN*/'),b=html.indexOf('/*API-END*/');
need(a>0&&b>a,'API markers missing in public/index.html');
const shim=`const POST={calculate:E.calculate,bands:E.bands,compare:E.compare,benefits:E.benefits,tax:E.taxProfile,dashboard:E.dashboard,engagement:E.engagement};
const api=(p,b)=>new Promise((ok,no)=>{try{const r=p.split('/');let o;
 if(b!==undefined&&POST[r[0]])o=POST[r[0]](b);else if(r[0]==='meta')o={roles:E.ROLES,levels:E.LEVELS,countries:E.countries()};
 else if(r[0]==='minimum-wage')o=E.minWage(r[1]);else if(r[0]==='data-quality')o=E.quality();else throw new Error('Not found');
 ok(JSON.parse(JSON.stringify(o)))}catch(e){no(e)}});`;
html=html.slice(0,a)+shim+html.slice(b+'/*API-END*/'.length);
need(html.includes('<script>\nconst $='),'script start marker not found');
const dashB64=Buffer.from(read('public/Global_Compensation_Dashboard_2026.html'),'utf8').toString('base64');
const embed=`const DASH_B64='${dashB64}';\nconst DASH_HTML=()=>new TextDecoder('utf-8').decode(Uint8Array.from(atob(DASH_B64),c=>c.charCodeAt(0)));\n`;
html=html.replace('<script>\nconst $=',()=>'<script>\n'+engineJs+embed+'const $=');
const src=' src="Global_Compensation_Dashboard_2026.html"';
need(html.includes(src),'dashboard iframe src not found');
html=html.replace(src,'');
const hook="f.onload=()=>{try{const h=f.contentDocument.documentElement.scrollHeight;f.style.height=Math.max(1200,h+12)+'px'}catch(e){}};";
need(html.includes(hook),'iframe onload hook not found');
html=html.replace(hook,()=>hook+'\n  f.srcdoc=DASH_HTML();');
need(!html.includes('fetch('),'fetch() left in single-file build');

const out={'public/engine.bundle.js':bundle,'index.html':html};
if(process.argv.includes('--check')){
  const stale=Object.keys(out).filter(f=>!fs.existsSync(path.join(root,f))||fs.readFileSync(path.join(root,f),'utf8')!==out[f]);
  if(stale.length){console.error('STALE generated files (run npm run build): '+stale.join(', '));process.exit(1)}
  console.log('generated files are up to date');
}else{
  for(const f of Object.keys(out)){fs.writeFileSync(path.join(root,f),out[f]);console.log(f,out[f].length,'bytes')}
}
